name: stufe
description: "A Flutter App for managing student life."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

analyzer:
  errors:
    invalid_annotation_target: ignore

dependencies:
  collection: ^1.19.1
  country_picker: ^2.0.27
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  google_sign_in: ^7.1.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env.local
    - .env.prod
